/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;
import java.net.URL;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.WebDriver;

public class App {

    public static void main(String[] args) {
        URL gridUrl = null;
        
        try {
          gridUrl = new URL("http://ec2-44-211-129-23.compute-1.amazonaws.com:4444/wd/hub");
        } catch(Exception e) {
            System.out.println("Couldn't create URL");
            System.exit(1);
        }

        ChromeOptions options = new ChromeOptions();
        WebDriver driver = new RemoteWebDriver(gridUrl, options);
        driver.get("https://www.google.com");

        // Print the page title
        System.out.println("Page Title: " + driver.getTitle());

        // Close the browser
        driver.quit();
    }
}
